config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :exercises, only: [:index, :show] do
        resources :scores, only: [:create, :update]
      end
      # Do we want to move this into nested within exercises?
      resources :scores, only: [:index, :show]
    end
  end

  get 'exercises/unlocks' => 'exercises#unlocks'
  post 'exercises/unlock/:id' => 'exercises#unlock', as: 'exercise_unlock'
  resources :exercises, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/exercise.rb
# == Schema Information
#
# Table name: exercises
#
#  id          :integer          not null, primary key
#  name        :string           default(""), not null
#  image_url   :string
#  description :text             default(""), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Exercise < ActiveRecord::Base
  validates :name, :image_url, length: { maximum: 255 }
  validates :name, presence: true

  has_many :scores, dependent: :destroy
  has_many :users, through: :scores
end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id          :integer          not null, primary key
#  score       :integer          default(0), not null
#  discipline  :string
#  user_id     :integer
#  exercise_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :exercise

  validates :discipline, length: { maximum: 255 }
  validates :score, :user, :exercise, presence: true
end

app/models/unlock.rb
class Unlock < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :user

  validates :user, :exercise, presence: true
  validates :exercise, uniqueness: { scope: :user_id }

  def self.unlock(user, exercise)
    unlock = self.initialize_unlock(user, exercise)
    unlock.save ? true : false
  end

  def self.unlock!(user, exercise)
    unlock = self.initialize_unlock(user, exercise)
    unlock.save! ? true : false
  end

  def self.unlock_initial_exercises(user)
    exercise = Exercise.first
    unlock(user, exercise)
  end

  private

  def self.initialize_unlock(user, exercise)
    unlock = Unlock.find_or_initialize_by(
      user: user,
      exercise: exercise)
    unlock.update(unlocked_at: Time.now)
    unlock
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_token_authenticatable

  validates :email, length: { maximum: 255 }

  has_many :scores, dependent: :destroy
  has_many :unlocks, dependent: :destroy
  has_many :exercises, through: :unlocks

  after_create :unlock_initial_exercises

  private

  def unlock_initial_exercises
    Unlock.unlock_initial_exercises(self)
  end
end

app/controllers/api/v1/exercises_controller.rb
class Api::V1::ExercisesController < BaseApiController
  actions :index, :show
end

app/controllers/api/v1/scores_controller.rb
class Api::V1::ScoresController < BaseApiController
  actions :index, :show, :create, :update, :destroy

  def create
    @score = Score.new(
      user: current_user,
      exercise: Exercise.find(params[:exercise_id]),
      discipline: params[:score][:discipline],
      score: params[:score][:score]
    )
    create!
  end

  def permitted_params
    params.permit(score: [
      :score,
      :discipline,
      :user_id,
      :exercise_id
    ])
  end
end

app/controllers/application_controller.rb
require_relative '../facades/exercises_facade'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_api_controller.rb
require 'responders/json_responder'

class BaseApiController < InheritedResources::Base
  acts_as_token_authentication_handler_for User

  respond_to :json
  responders :json

  def collection
    limit_per_page = params[:per_page] || nil
    @q = end_of_association_chain
    @q = @q.search(params[:q])
    @q = @q.result

    @total_count = @q.length
    limit_per_page ||= @total_count

    # Pagination
    if params[:from]
      @q = @q.with_name_from(params[:from][:name], limit_per_page) if params[:from][:name]
      @q = @q.with_field_from(params[:from][:field], params[:from][:value]) if params[:from][:field]
    end

    @q.limit(limit_per_page)
  end

  def default_serializer_options
    { meta: { pagination: { total_objects: @total_count } } }
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = ExercisesFacade.new(current_user)
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def unlocks
    # TODO: refactor into class method?
    # Maybe a Facade with tiers etc?
    all_exercises = Exercise.all
    @locked_exercises = all_exercises.select {|exercise| !current_user.exercises.include? exercise }
  end

  def unlock
    exercise = Exercise.find(params[:id])
    Unlock.unlock(current_user, exercise)
    redirect_to exercises_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in well") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/exercises/_tier.html.erb
<div class="panel panel-default panel-primary">
  <div class='panel-heading'>Tier <%= tier %></div>
  <div class="panel-body">
    <table class='exercise-list table'>
      <tr>
        <th>Name</th>
        <th class='center'>High Score</th>
      </tr>
      <% @exercises.exercises_for_tier(tier).each do |exercise| %>
        <tr>
          <td><%= link_to exercise.name, exercise %></td>
          <%# TODO: this is hacky, sort it out! %>
          <td class='center'><%= exercise.scores.where(user: current_user).order(:created_at).last.try(:score) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/exercises/index.html.erb
<% @exercises.tiers.each do |tier| %>
  <%= render partial: 'exercises/tier', locals: { tier: tier } %>
<% end %>

<div class='well center'>
  <p><%= link_to 'Unlock more exercises', exercises_unlocks_path %></p>
</div>

app/views/exercises/show.html.erb
<%# TODO: render server-side %>
<%= react_component('Exercise', { exercise: @exercise, url: api_v1_exercise_scores_path(@exercise) }) %>

app/views/exercises/unlocks.html.erb
<div class="panel panel-default panel-primary">
  <div class='panel-heading'>Unlock a new exercise</div>
  <div class="panel-body">
    <% if @locked_exercises.any? %>
      <table class='exercise-list table'>
        <tr>
          <th>Name</th>
        </tr>
        <% @locked_exercises.each do |exercise| %>
          <tr>
            <td><%= link_to exercise.name, exercise_unlock_path(exercise.id), method: :post %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p>No more exercises available to unlock!</p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Drumbeat!</h1>
  <p class="lead">Practice your rudiments, record your progress, and, share with friends (maybe at some point)!!!</p>
  <p><%= link_to 'Go to my exercises', exercises_path, class:'btn btn-lg btn-success', role: 'button' %></p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h3>Recently played rudiments</h3>
    <h4>Subheading</h4>
    <p>Todo: these things would be nice, order rudiments based on when you scored them.</p>

    <h4>Subheading</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

    <h4>Subheading</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>

  <div class="col-lg-6">
    <h3>New rudiments</h3>
    <h4>Subheading</h4>
    <p>Rudiments that don't yet have a score set.</p>

    <h4>Subheading</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

    <h4>Subheading</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 50px;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Drumbeat', root_url, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <% if current_user %>
           <li><%= link_to 'Exercises', exercises_path %></li>
           <li class="divider"></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="divider"></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <meta name="description" content="Learn drum rudiments in style!">
      <meta name="author" content="chrisjohnjewell@gmail.com">
      <!-- TODO <link rel="icon" href="../../favicon.ico"> -->

    <title>Drumbeat</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="container" id='main-container'>

      <%= flash_messages %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <meta name="description" content="Learn drum rudiments in style!">
      <meta name="author" content="chrisjohnjewell@gmail.com">
      <!-- TODO <link rel="icon" href="../../favicon.ico"> -->

    <title>Drumbeat</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="container" id='main-container'>

      <%= flash_messages %>
      <div class='well'>
        <div class='container'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise_layout.html.erb
<div class='well'>
  <div class='container'>

    <%= yield %>
  </div>
</div>